server:
  port: 8765
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: service-feign

feign:
  hystrix:
    #开启feign的hystrix支持,默认是false
    enabled: true
